### ISSUE TITLE
Hazelcast-Kubernetes plugin does not work in OrientDB cluster mode

### ISSUE THREAD

**Issue by CassieAin** [hazelcast/hazelcast-kubernetes#111]
I have been trying to setup OrientDB in a distributed mode by following the instructions in Readme about setting up Hazelcast plugin for Kubernetes. I am using a stateful set with quite a lot of volumes. Also, I took a DNS approach. I checked from all the pods in a cluster that they find each other. Also, the same selectors defined in a headless service can be applied to the pods. It seems like there are no problems in a Kubernetes cluster setup. Also, I checked that I defined a proper DNS name for the service.
But I see in the logs for each pod that they form a single-member cluster instead of joining a shared one:

```
Members [1] {
	Member [ip-address]:5701 - ... this
}
 [DiscoveryJoiner]
```
Also, OrientDB enters a shared mode and all the database related configs are set up. What could be the cause of the problem?
That`s headless service configuration:

```
kind: Service
apiVersion: v1
metadata:
  name: orientdbservice
  labels:
    service: orientdb
    type: headless-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    service: orientdb
    type: container-deployment
  ports:
  - port: 2424
    name: port-binary
  - port: 2480
    name: port-http
  - port: 5701
    name: hazelcast
```

This is my hazelcast file:

```
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.3.xsd"
           xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
        <name>orientdb-test-cluster-1</name>
        <password>Ml835yTe92</password>
    </group>
    <properties>
        <property name="hazelcast.discovery.enabled">true</property>
    </properties>
    <network>
        <join>
            <multicast enabled="false"/>
            <tcp-ip enabled="false"/>
            <discovery-strategies>
                <discovery-strategy enabled="true"
                                    class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy">
                    <properties>
                        <property name="service-dns">orientdbservice.default.svc.cluster.local</property>
                        <property name="service-dns-timeout">10</property>
                    </properties>
                </discovery-strategy>
            </discovery-strategies>
        </join>
    </network>
</hazelcast>
```

**Comment by leszko** [comment]
@CassieAin Thanks for the question. Your configuration looks fine. Could you send here for following info?
1. Your Kubernetes yaml configuration for the StatefulSet
2. The output of `kubectl describe service/orientdbservice`
3. Are you running in the namespace `default`?

**Comment by CassieAin** [comment]
@leszko  I am going to answer in the reverse order as StatefulSet description will take most of the space.
3. Yes, I am running in the default namespace
2.  Here is the output of `kubectl describe service/orientdbservice`
```
Name:              orientdbservice
Namespace:         default
Labels:            service=orientdb
                   type=headless-service
Annotations:       kubectl.kubernetes.io/last-applied-configuration:
                     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"service":"orientdb","type":"headless-service"},"name":"orientd...
Selector:          service=orientdb,type=container-deployment
Type:              ClusterIP
IP:                None
Port:              port-binary  2424/TCP
TargetPort:        2424/TCP
Endpoints:         172.17.0.4:2424,172.17.0.5:2424,172.17.0.6:2424
Port:              port-http  2480/TCP
TargetPort:        2480/TCP
Endpoints:         172.17.0.4:2480,172.17.0.5:2480,172.17.0.6:2480
Port:              hazelcast  5701/TCP
TargetPort:        5701/TCP
Endpoints:         172.17.0.4:5701,172.17.0.5:5701,172.17.0.6:5701
Session Affinity:  None
Events:            <none>
```

1. My StatefulSet  configuration (I run server_config_template.sh script to create a template for orientdb-server-config.xml file where the nodeName value is replaced with the  pod_name env value):
```
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: orientdbservice
spec:
  serviceName: orientdbservice
  replicas: 3
  selector:
    matchLabels:
      service: orientdb
      type: container-deployment
  template:
    metadata:
      labels:
        service: orientdb
        type: container-deployment
    spec:
      containers:
      - name: orientdbservice
        image: orientdb:2.2.36
        command: ["/bin/sh","-c", " cp /configs/* /orientdb/config/ ;  chmod +x /orientdb/config/server_config_template.sh ;  sh /orientdb/config/server_config_template.sh ; /orientdb/bin/server.sh -Ddistributed=true" ]
        env:
        - name: ORIENTDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orientdb-password
              key: password.txt
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 2424
          name: port-binary
        - containerPort: 2480
          name: port-http
        - containerPort: 5701
          name: hazelcast
        volumeMounts:
        - name: config
          mountPath: /orientdb/config
        - name: orientdb-config-hazelcast
          mountPath: /configs/hazelcast.xml
          subPath: hazelcast.xml
        - name: orientdb-config-template-server
          mountPath: /configs/server_config_template.sh
          subPath: server_config_template.sh
        - name: orientdb-config-backups
          mountPath: /configs/backups.json
          subPath: backups.json
        - name: orientdb-config-events
          mountPath: /configs/events.json
          subPath: events.json
        - name: orientdb-config-distributed
          mountPath: /configs/default-distributed-db-config.json
          subPath: default-distributed-db-config.json
        - name: orientdb-config-client-logs
          mountPath: /configs/orientdb-client-log.properties
          subPath: orientdb-client-log.properties
        - name: orientdb-config-server-logs
          mountPath: /configs/orientdb-server-log.properties
          subPath: orientdb-server-log.properties
        - name: orientdb-databases
          mountPath: /orientdb/databases
        - name: orientdb-backup
          mountPath: /orientdb/backup
        - name: orientdb-data
          mountPath: /orientdb/bin/data
      volumes:
      - name: config
        emptyDir: {}
      - name: orientdb-config-hazelcast
        configMap:
          name: orientdb-configmap-hazelcast
      - name: orientdb-config-template-server
        configMap:
          name: orientdb-configmap-template-server
      - name: orientdb-config-backups
        configMap:
          name: orientdb-configmap-backups
      - name: orientdb-config-events
        configMap:
          name: orientdb-configmap-events
      - name: orientdb-config-distributed
        configMap:
          name: orientdb-configmap-distributed
      - name: orientdb-config-client-logs
        configMap:
          name: orientdb-configmap-client-logs
      - name: orientdb-config-server-logs
        configMap:
          name: orientdb-configmap-server-logs
      - name: orientdb-data
        hostPath:
          path: /import_data
          type: Directory
  volumeClaimTemplates:
  - metadata:
      name: orientdb-databases
      labels:
        service: orientdb
        type: pv-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 40Gi
  - metadata:
      name: orientdb-backup
      labels:
        service: orientdb
        type: pv-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
```
