### ISSUE TITLE
Does hazelcast-kubernetes support istio?

### ISSUE THREAD

**Issue by SmileSees** [hazelcast/hazelcast-kubernetes#118]
I was using hazelcast-kubernetes in the k8s cluster before, when scale two hazelcast-kubernetes StatefulSet, they can join together, and working with my services.

Recently our services injected with istio. I try to inject the hazelcast-kubernetes with istio, it was running, but those two hazelcast-kubernetes cannot join together.

Do you know how to configure with istio for hazelcast-kubernetes? Thanks.

**Comment by mesutcelik** [comment]
Hi @SmileSees ,
We haven't tested Istio yet but planning to have a look at it soon. It would be appreciated if you can provide any feedback or contribution.

**Comment by SmileSees** [comment]
Hi @mesutcelik, I have tested with some scenarios,
1. No istio involved, 2 hazelcast pod, 1 our service pod, in our service's log, can see there are 3 members in the members section.
2. Hazlecast is not inject with istio, our service injected with istio, in our service's log, there is our 1 member in the member section.

There are some logs,

com.hazelcast.nio.tcp.TcpIpConnectionManager.null [172.50.9.98]:6701 [dev] [3.10] Established socket connection between /172.50.9.98:50455 and /172.50.9.89:5701
com.hazelcast.nio.tcp.TcpIpConnectionManager.null [172.50.9.98]:6701 [dev] [3.10] Established socket connection between /172.50.9.98:48617 and /172.50.3.74:5701
com.hazelcast.nio.tcp.TcpIpConnection.null [172.50.9.98]:6701 [dev] [3.10] Connection[id=3, /172.50.9.98:50455->/172.50.9.89:5701, endpoint=[172.50.9.89]:5701, alive=false, type=NONE] closed. Reason: Connection closed by the other side
com.hazelcast.nio.tcp.TcpIpConnection.null [172.50.9.98]:6701 [dev] [3.10] Connection[id=4, /172.50.9.98:48617->/172.50.3.74:5701, endpoint=[172.50.3.74]:5701, alive=false, type=NONE] closed. Reason: Connection closed by the other side

**Comment by leszko** [comment]
@SmileSees , could you paste here your k8 configuration (yaml)?

**Comment by SmileSees** [comment]
Hi @leszko , you can refer to https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/kubernetes/samples/embedded, I  also tried this code sample and deployment sample, it have the same result with my service.
1. When istio not involved, the 2 pods can join together.
2. After injected the service with istio, the 2 pods cannot join as a cluster.

**Comment by leszko** [comment]
Sorry, I don't have much knowledge about Istio, but I'll try to help. Could you write exactly what changes you made to https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/kubernetes/samples/embedded, so that id does not work?

**Comment by SmileSees** [comment]
Hi @leszko, I only add two names for hazelcast ports.  
Deployment.yaml:


	apiVersion: apps/v1
	kind: Deployment
	metadata:
	  name: hazelcast-embedded
	spec:
	  replicas: 2
	  selector:
	    matchLabels:
	      app: hazelcast-embedded
	  template:
	    metadata:
	      labels:
	        app: hazelcast-embedded
	    spec:
	      containers:
	        - name: hazelcast-embedded
	          image: docker.io/leszko/hazelcast-kubernetes-embedded-sample
	          imagePullPolicy: Always
	          ports:
	          - containerPort: 5701
	            name: tcp-hazelcast
	          - containerPort: 8080
	            name: http-app
	
	---
	
	apiVersion: v1
	kind: Service
	metadata:
	  name: hazelcast-embedded
	spec:
	  type: LoadBalancer
	  selector:
	    app: hazelcast-embedded
	  ports:
	  - name: tcp-hazelcast
	    port: 5701
	  - name: http-app
	    port: 8080

rbac.yaml:

	---
	apiVersion: rbac.authorization.k8s.io/v1
	kind: ClusterRoleBinding
	metadata:
	  name: default-cluster
	roleRef:
	  apiGroup: rbac.authorization.k8s.io
	  kind: ClusterRole
	  name: view
	subjects:
	- kind: ServiceAccount
	  name: default
	  namespace: default

See the logs, 
[hazelcast-embedded-istio.log](https://github.com/hazelcast/hazelcast-kubernetes/files/2638665/hazelcast-embedded-istio.log)

**Comment by SmileSees** [comment]
The logs above was using command: 
`kubectl apply -f <(istioctl kube-inject -f deployment.yaml)`

**Comment by leszko** [comment]
Could you paste also the resources that were created in k8? Meaning the output of `kubectl get all` and `kubectl describe` for the service and POD?

**Comment by leszko** [comment]
Ok, I had a look, but still have no clear answer, because I lack the knowledge about Istio. Here are my thoughts:
1. Discovery itself works fine, you can see in the POD logs, that one Hazelcast member tried to connect to another Hazelcast member (`[172.50.15.13]:5701 [dev] [3.11] Connecting to /172.50.1.28:5701`). They use the correct IP addresses.
2. I'm not sure what does the Istio Proxy Container in each POD. There is something like that in the POD description: 
```
    Args:
      -p
      15001
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x
      
      -b
      5701, 8080,
      -d
```

Does it mean that the standard port of Hazelcast (`5701`) is changed to some other port? That could be the reason it does not work.

3. I'd check with the curl command if you can connect to the Hazelcast member. Meaning something like: `curl 172.50.1.28:5701/hazelcast/health`. The command must be executed from one of the PODs in the same cluster. For example you can exec to one of the members like `kubectl exec -i hazelcast-embedded-68d489dd6-6r74m /bin/bash` and execute the curl command there. If it doesn't work, then the Hazelcast port is not exposed correctly from the POD, meaning that Istio Proxy does something weird with it.

**Comment by kti-nicole** [comment]
Hi, we're having the same issue. The curl in a similar situation gives a generic timeout. If it helps, on a successful connection (without istio) the connection comes from the pod IP, but with istio it's coming from the sidecar on localhost; 

`Dec 18, 2018 7:55:59 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [10.32.0.132]:5701 [dev] [3.9.3] Connection[id=49, /127.0.0.1:5701->/127.0.0.1:50510, endpoint=null, alive=false, type=REST_CLIENT] closed. Reason: Connection closed by the other side
Dec 18, 2018 7:56:09 PM com.hazelcast.nio.tcp.TcpIpAcceptor
INFO: [10.32.0.132]:5701 [dev] [3.9.3] Accepting socket connection from /127.0.0.1:50576
Dec 18, 2018 7:56:09 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [10.32.0.132]:5701 [dev] [3.9.3] Established socket connection between /127.0.0.1:5701 and /127.0.0.1:50576
Dec 18, 2018 7:56:09 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [10.32.0.132]:5701 [dev] [3.9.3] Connection[id=50, /127.0.0.1:5701->/127.0.0.1:50576, endpoint=null, alive=false, type=REST_CLIENT] closed. Reason: Connection closed by the other side`

Istio only supports a few protocols, but I would expect the curl to work since http is one of them. It leaves in some headers that could be breaking things, since istio looks to not use http for general communication?

**Comment by SmileSees** [comment]
We use https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/kubernetes/samples/springboot-k8s-hello-world this example, and put **the-server** in the k8s env, let **the-client** inject with istio, and add a **ServiceEntry** with server pod's ip find out that the-client service be able to connect the-server cluster, can see the member list from the-client logs.
Example for our serviceentry:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: hazelcast-external
spec:
  hosts:
  - "*"
  addresses:
  - 172.50.0.0/16 # pod cidr
  ports:
  - name: tcp
    number: 5701
    protocol: tcp
  location: MESH_EXTERNAL
```
But we nerver succeed with embedded example codes, the servers cannot join together after inject with istio.

**Comment by lovepocky** [comment]
> We use https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/kubernetes/samples/springboot-k8s-hello-world this example, and put **the-server** in the k8s env, let **the-client** inject with istio, and add a **ServiceEntry** with server pod's ip find out that the-client service be able to connect the-server cluster, can see the member list from the-client logs.
> Example for our serviceentry:
> 
> ```
> apiVersion: networking.istio.io/v1alpha3
> kind: ServiceEntry
> metadata:
>   name: hazelcast-external
> spec:
>   hosts:
>   - "*"
>   addresses:
>   - 172.50.0.0/16 # pod cidr
>   ports:
>   - name: tcp
>     number: 5701
>     protocol: tcp
>   location: MESH_EXTERNAL
> ```
> But we nerver succeed with embedded example codes, the servers cannot join together after inject with istio.

I have succeed to setup cluster with configuration above:

```
# https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pod2pod-hazel
spec:
  hosts:
    - hazel # not used
  addresses:
    - 10.233.0.1/16 # cluster ip cidr
  ports:
    - number: 5701
      name: hzport
      protocol: TCP
    - number: 15701 # fixed eventbus port for vertx
      name: eventbus
      protocol: TCP
  location: MESH_INTERNAL
  resolution: NONE
```

**Comment by leszko** [comment]
@lovepocky Could you describe in more details how you made hazelcast [springboot-k8-hello-world](https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/kubernetes/samples/springboot-k8s-hello-world) work in Istio?

I actually tried the following, but it didn't work.
1. Install Istio into k8 cluster
2. Create `service-entry.yaml` as you described.
```
# https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pod2pod-hazel
spec:
  hosts:
    - hazel # not used
  addresses:
    - <my-cluster-cidr> # cluster ip cidr
  ports:
    - number: 5701
      name: hzport
      protocol: TCP
    - number: 15701 # fixed eventbus port for vertx
      name: eventbus
      protocol: TCP
  location: MESH_INTERNAL
  resolution: NONE
```
3. Apply Service Entry.
```
kubectl apply -f service-entry.yaml
```

4. Start the sample with Istio.
```
kubectl apply -f <(istioctl kube-inject -f deployment.yaml)
```
5. Client fails, because it seems all its outbound connections are blocked by the Envoy proxy.

**Comment by SmileSees** [comment]
The deployment.yaml have server, client and managerment center. Put the client into another yaml file. Only inject the client related file:
kubectl apply -f <(istioctl kube-inject -f client.yaml)
And only apply server and management center in k8s env, by:
kubectl apply -f server.yaml

@leszko, pls try above.

**Comment by lovepocky** [comment]
@leszko Oh, I means that using `ServiceEntry` will not block the outbound port in my last comment, i.e. {this pod ip}:{some random port} -> {other pod ip}:5701
I have setup cluster of vertx-cluster with hazel, not spring hello-world demo.

**Comment by leszko** [comment]
@SmileSees @lovepocky I try, but still cannot get it working. I use the following code: https://github.com/leszko/hazelcast-code-samples/tree/istio-test/hazelcast-integration/kubernetes/samples/springboot-k8s-hello-world

1. I create a cluster on GKE and check the CIDR.

```
$ gcloud container clusters describe <cluster-name> --zone us-central1-a | grep -e clusterIpv4Cidr
clusterIpv4Cidr: 10.12.0.0/14
```

2. I update `service-entry.yaml` with my CIDR and apply it.

```
$ kubectl apply -f service-entry.yaml
```

3. I start the server and management center.

```
kubectl apply -f deployment-server.yaml
```

4. I start the client with Istio.

```
kubectl apply -f <(istioctl kube-inject -f deployment-client.yaml)
```

Then I got the following error in the client:
```
2019-03-25 15:53:23.979  WARN 1 --- [ient_0.cluster-] c.h.c.c.ClientConnectionManager          : hz.client_0 [k8s] [3.10.4] Could not connect to cluster, shutting down the client. Unable to connect to any address! The following addresses were tried: [[10.12.1.9]:5701]
```

Which seems that the Envoy blocks the call from Hazelcast Client. Any ideas what can help?

**Comment by SmileSees** [comment]
Hi@leszko, I just tried with your steps, it worked in my cluster.  My serviceentry host is "*", and cidr is "172.50.0.0/16", I am not sure if it affect anything.

    NAME                     READY   STATUS    RESTARTS   AGE     IP             NODE        NOMINATED NODE
    pod-hazelcast-client-0   2/2     Running   0          4m51s   172.50.10.77   10.0.0.17   <none>
    pod-hazelcast-client-1   2/2     Running   0          3m14s   172.50.4.75    10.0.0.10   <none>
    pod-hazelcast-server-0   1/1     Running   0          8m6s    172.50.6.33    10.0.0.13   <none>
    pod-hazelcast-server-1   1/1     Running   0          6m59s   172.50.4.74    10.0.0.10   <none>

You can see the client have two containers in each pod which were injected with istio.
The client logs
        Members [2] {
           Member [172.50.6.33]:5701 - 2a297d87-aa84-4cda-a2d5-6f332197e0e2
           Member [172.50.4.74]:5701 - 735c02fb-86d7-488b-be7a-a6387ffff334
    }

**Comment by leszko** [comment]
@SmileSees interesting.... which Istio version do you use?

**Comment by SmileSees** [comment]
@leszko I am using istio 1.0.2 version with auth-demo.yaml.

**Comment by leszko** [comment]
@SmileSees Thanks, it works in 1.0.2 indeed! Super weird, Istio versions:
- 1.0.2 - works fine
- 1.0.6 - does not work
- 1.1.0 - even the main Istio Bookinfo sample doesn't work!

Anyway, thanks a lot for the help!

**Comment by leszko** [comment]
I actually re-tested Hazelcast on Istio (1.1.0) and it apparently it works fine (even without any need of the MESH_INTERNAL or MESH_EXTERNAL configuration). So, it might have been my environment (I either had old `istioctl` installed or not enough resources on the k8 cluster).

Closing it for now. Feel free to reopen if there are any issues with how Hazelcast works with Istio >= 1.1.0.

**Comment by yacut** [comment]
@leszko Unfortunately, hazelcast does not work with istio even with istio version 1.3.4 
I used the same setup as @SmileSees  did: https://github.com/hazelcast/hazelcast-kubernetes/issues/118#issuecomment-443632542

and have this error:
```
[#|2019-11-08T15:38:44.223+0000|WARNING|com.hazelcast.nio.tcp.TcpIpConnection|_ThreadID=112;_ThreadName=hz._hzInstance_2_development.IO.thread-in-0;_TimeMillis=1573227524223;_LevelValue=900;|
  [172.31.44.112]:4900 [development] [3.12] Connection[id=127, /172.31.44.112:41425->/172.31.18.139:5900, qualifier=null, endpoint=[172.31.18.139]:5900, alive=false, type=NONE] closed. Reason: Exception in Connection[id=127, /172.31.44.112:41425->/172.31.18.139:5900, qualifier=null, endpoint=[172.31.18.139]:5900, alive=true, type=NONE], thread=hz._hzInstance_2_development.IO.thread-in-0
java.lang.IllegalStateException: Unknown protocol:
	at com.hazelcast.nio.tcp.UnifiedProtocolDecoder.onRead(UnifiedProtocolDecoder.java:107)
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:135)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:369)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:354)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:280)
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:235)
|#]
```

**Comment by mesutcelik** [comment]
Can you please give more info regarding your configuration?
Is this happening in the hazelcast member clustering part or when connecting via hazelcast client to hazelcast cluster?

I just recently tried it with Istio 1.3.3 and member discovery working fine.

**Comment by yacut** [comment]
I have a statefulset, the first  pod starts well but the second one tries to connect to the cluster without success.

**Comment by mesutcelik** [comment]
I had tried with auto sidecar injection enabled `kubectl label namespace default istio-injection=enabled` and `helm install stable/hazelcast` and  but it was istio 1.3.3 with those installation [instructions](https://istio.io/docs/setup/install/helm/#option-1-install-with-helm-via-helm-template). I will try with 1.3.4 release too and update here.

**Comment by yacut** [comment]
I use hazelcast with payara in k8s discovery mode. Could it be a problem?

**Comment by mesutcelik** [comment]
It shouldn't...

Is global mTLS enabled for your deployment?
https://istio.io/docs/tasks/security/authn-policy/#globally-enabling-istio-mutual-tls

What does that return?
`kubectl describe meshpolicy default`

**Comment by yacut** [comment]
Yes, mTLS is enabled. In the destination rule is also enabled...

```sh
kubectl describe meshpolicy default
Name:         default
Namespace:
Labels:       app=security
              chart=security
              heritage=Tiller
              release=istio
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"authentication.istio.io/v1alpha1","kind":"MeshPolicy","metadata":{"annotations":{},"labels":{"app":"security","chart":"secu...
API Version:  authentication.istio.io/v1alpha1
Kind:         MeshPolicy
Metadata:
  Creation Timestamp:  2019-10-14T07:29:12Z
  Generation:          1
  Resource Version:    1747093
  Self Link:           /apis/authentication.istio.io/v1alpha1/meshpolicies/default
  UID:                 51c94c48-ee54-11e9-8f65-0a952dda548a
Spec:
  Peers:
    Mtls:
Events:  <none>
```

**Comment by mesutcelik** [comment]
TLS/SSL is an enterprise feature of Hazelcast. That is why it does not work for you.
https://docs.hazelcast.org/docs/3.12.4/manual/html-single/#tlsssl

If you change it permissive then you will most probably see Hazelcast members will discover each other
```
kubectl apply -f - <<EOF
apiVersion: "authentication.istio.io/v1alpha1"
kind: "MeshPolicy"
metadata:
  name: "default"
spec:
  peers:
  - mtls:
      mode: PERMISSIVE
EOF
```

**Comment by yacut** [comment]
I don't unterstand  what this has to do with the hazelcast tls feature? Istio Proxy should do tls encryption, not hazelcast itself. This is one of the main advantages of istio.

**Comment by yacut** [comment]
cc @mesutcelik 
related to https://github.com/hazelcast/hazelcast-kubernetes/issues/160

**Comment by mesutcelik** [comment]
Thanks @yacut , I am checking with @kwart and will update the issue.

**Comment by mesutcelik** [comment]
Can you give a try to this? AFAIS, mTLS does not work for Hazelcast with `ClusterIP` but with headless mode only.

I tested with `1.14.8-gke.12` on GKE and Istio version 1.3.4

You can inject manually
`istioctl kube-inject -f hazelcast-statefulset-headless.yaml |kubectl apply -f -` 

or enable autoinject
```
kubectl label namespace default istio-injection=enabled
kubectl apply -f hazelcast-statefulset-headless.yaml 
```



hazelcast-statefulset-headless.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-configuration
data:
  hazelcast.yaml: |-
    hazelcast:
      network:
        join:
          kubernetes:
            enabled: true
            service-name: hazelcast-embedded
          multicast:
            enabled: false

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast-embedded
spec:
  serviceName: hazelcast-embedded
  replicas: 3
  selector:
    matchLabels:
      app: hazelcast-embedded
  template:
    metadata:
      labels:
        app: hazelcast-embedded
    spec:
      containers:
        - name: hazelcast-embedded
          image: hazelcast/hazelcast:3.12.4
          imagePullPolicy: Always
          ports:
          - containerPort: 5701
          volumeMounts:
          - name: hazelcast-storage
            mountPath: /data/hazelcast
          env:
          - name: JAVA_OPTS
            value: "-Dhazelcast.rest.enabled=true -Dhazelcast.config=/data/hazelcast/hazelcast.yaml"
      volumes:
      - name: hazelcast-storage
        configMap:
          name: hazelcast-configuration

---

apiVersion: v1
kind: Service
metadata:
  name: hazelcast-embedded
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: hazelcast-embedded
  ports:
  - name: tcp-hazelcast
    port: 5701
```

**Comment by yacut** [comment]
@mesutcelik @kwart Thank you for the solution. I was able to start hazelcast cluster and make sure it works with Istio mTLS. 
Unfortunately, payara micro doesn't work with the same setup. Maybe the default hazelcast settings for payara micro are different from the standard hazelcast?

Here is my setup:
```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payara-micro
spec:
  serviceName: payara-micro
  replicas: 2
  selector:
    matchLabels:
      app: payara-micro
  template:
    metadata:
      labels:
        app: payara-micro
    spec:
      serviceAccountName: default # need to set rbac permissions
      containers:
        - name: payara-micro
          image: payara/micro:5.193.1
          imagePullPolicy: Always
          command:
            - "java"
            - "-jar"
            - "/opt/payara/payara-micro.jar"
            - "--name"
            - "$(POD_NAME)"
            - "--clustermode"
            - "kubernetes:default,payara-micro-headless"
          ports:
            - name: http-app
              containerPort: 8080
            - name: tcp-hazelcast
              containerPort: 6900
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  name: payara-micro-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: payara-micro
  ports:
    - name: tcp-hazelcast
      port: 6900

---
apiVersion: v1
kind: Service
metadata:
  name: payara-micro
spec:
  type: ClusterIP
  selector:
    app: payara-micro
  ports:
    - name: http-app
      port: 8080

```

Could you give me a clue?

**Comment by mesutcelik** [comment]
Did you try passing `payara-micro-headless` as a service-name in hazelcast configuration? I think you need to check payara how to configure Hazelcast as it is embedded inside the payara-micro

**Comment by yacut** [comment]
Yes, I tried it also. It works:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-configuration
data:
  hazelcast.xml: |-
    <?xml version="1.0" encoding="UTF-8" ?>
    <hazelcast xmlns="http://www.hazelcast.com/schema/config"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.hazelcast.com/schema/config
              http://www.hazelcast.com/schema/config/hazelcast-config-4.0.xsd">
        <network>
          <port auto-increment="false" port-count="100">5701</port>
          <join>
              <multicast enabled="false" />
              <kubernetes enabled="true">
                  <namespace>default</namespace>
                  <service-name>payara-micro-headless</service-name>
              </kubernetes>
          </join>
      </network>
    </hazelcast>

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payara-micro
spec:
  serviceName: payara-micro
  replicas: 2
  selector:
    matchLabels:
      app: payara-micro
  template:
    metadata:
      labels:
        app: payara-micro
    spec:
      serviceAccountName: ilert-monolith
      containers:
        - name: payara-micro
          image: payara/micro:5.193.1
          imagePullPolicy: Always
          command:
            - "java"
            - "-jar"
            - "/opt/payara/payara-micro.jar"
            - "--name"
            - "$(POD_NAME)"
            - "--clustermode"
            - "kubernetes:default,payara-micro-headless"
            - "--hzconfigfile"
            - "/data/hazelcast/hazelcast.xml"
          ports:
            - name: http-app
              containerPort: 8080
            - name: tcp-hazelcast
              containerPort: 5701
          volumeMounts:
            - name: hazelcast-config
              mountPath: /data/hazelcast
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
      volumes:
        - name: hazelcast-config
          configMap:
            name: hazelcast-configuration

---
apiVersion: v1
kind: Service
metadata:
  name: payara-micro-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: payara-micro
  ports:
    - name: tcp-hazelcast
      port: 5701

---
apiVersion: v1
kind: Service
metadata:
  name: payara-micro
spec:
  type: ClusterIP
  selector:
    app: payara-micro
  ports:
    - name: http-app
      port: 8080


```
With is than payara micro issue. The official payara documentation says, if the `--hzconfigfile` flag is used then the default settings will be set to hazelcast defaults: https://docs.payara.fish/documentation/payara-server/hazelcast/configuration.html

@mesutcelik Thank you
