### ISSUE TITLE
DNS lookup error: name not found

### ISSUE THREAD

**Issue by matthjes** [hazelcast/hazelcast-kubernetes#179]
We are using the DNS lookup method for pod discovery, however, when we start a pod we get the following warnings:
```
{"timestamp":"2019-11-21T06:57:21.801Z","message":"[10.37.128.4]:5701 [blocs] [3.12.4] DNS lookup for serviceDns 'blocs-service-dns.svc-example.svc.cluster.local' failed: name not found","class":"com.hazelcast.spi.discovery.integration.DiscoveryService","thread":"main","level":"WARN","app_name":"blocs-service","app_version":"0.0.1-SNAPSHOT-196310a3"}
{"timestamp":"2019-11-21T06:57:21.813Z","message":"[10.37.128.4]:5701 [blocs] [3.12.4] DNS lookup for serviceDns 'blocs-service-dns.svc-example.svc.cluster.local' failed: name not found","class":"com.hazelcast.spi.discovery.integration.DiscoveryService","thread":"main","level":"WARN","app_name":"blocs-service","app_version":"0.0.1-SNAPSHOT-196310a3"}
...
```
I guess from the error message that the `service-dns` name (`blocs-service-dns.svc-example.svc.cluster.local`) could not be resolved.

The service is present:
```
kubectl get services
-> blocs-service-dns   ClusterIP   None             <none>        5701/TCP   20h
```

Here is the service description:
```
apiVersion: v1
kind: Service
metadata:
  name: blocs-service-dns
  namespace: svc-example
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: blocs-service
  ports:
    - name: hazelcast
      port: 5701
```

The 'service-dns' property is configured to be `blocs-service-dns.svc-example.svc.cluster.local`. When I perform a lookup inside the pod:
```
kubectl exec -ti blocs-service-69457df6cf-mzjl9 -- nslookup  blocs-service-dns.svc-example.svc.cluster.local
```
I get
```
Server:         100.64.0.10
Address:        100.64.0.10#53

Name:   blocs-service-dns.svc-example.svc.cluster.local
Address: 10.37.128.4
```
So it looks like the name can be resolved.

Does anyone have an idea why this is not working?

EDIT:
The warning only seems to come up when there is a single instance present. I just increased the replica count to 2 and now the cluster has been formed without any warnings.
