### ISSUE TITLE
Add `hostPort` for external smart client

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-kubernetes#182]
Currently, when we suggest [how to configure External Smart Client](https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/kubernetes/samples/external-client), we suggest creating a service per Pod (with Metacontroller).

The other option would be to use `hostPort`, we can add this option to the `hazelcast-kubernetes` plugin.

**Comment by hasancelik** [comment]
Smart clients need to be connected to all members at cluster but as you also mentioned at related [TDD](https://hazelcast.atlassian.net/wiki/spaces/PM/pages/1152450849/Enable+external+Smart+Client+for+Kubernetes+Cluster+Technical+Design+Document), `hostPort` is not suitable for it:

> It(hostPort) is not an option at the moment, since currently it's only possible to [statically assign the host port](https://github.com/kubernetes/kubernetes/issues/49792), which would make the limitation of scaling one Hazelcast POD / Kubernetes Node.

At kubernetes side, still there is no dynamic configuration for `hostPort`(range or random) as far as I can see. What is your plan to do that or am I missing something? 🙂 @leszko

**Comment by leszko** [comment]
Yeah, it's not possible to do it dynamically. But you could do what we actually do in case of Hazelcast Cloud and set up the static `hostPort` (there is even an option for that in our Helm Chart). Then, you're limited to the having max 1 Hazelcast POD per 1 Kubernetes Node (because the host port is status), but it may be good enough for some cases.

This GH issue is just to give the possibility of discovering something like that. Still the Hazelcast users need to take care of the correct Kubernetes-Hazelcast configuration.

**Comment by mikekuzak** [comment]
How do I set the port statically, is there a hostPort setting with the HZ operator?  Or basically the service should not auto generate a nodePort each time I deploy the service. I want to set the NodePort statically. 

```
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  clusterSize: 3
  clusterName: dev
  repository: hazelcast/hazelcast
  version: 5.4.0-slim-jdk17
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 3072Mi
      cpu: 8000m
#  highAvailabilityMode: NODE
  exposeExternally:
    type: Smart
    discoveryServiceType: NodePort
    memberAccess: NodePortExternalIP
  scheduling:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: hazelcast
            app.kubernetes.io/instance: hazelcast
            app.kubernetes.io/managed-by: hazelcast-platform-operator
```
