### ISSUE TITLE
Hazelcast ServiceAccount

### ISSUE THREAD

**Issue by ralphbaur** [hazelcast/hazelcast-kubernetes#213]
Is there an option to configure Hazelast to use a custom ServieAccount? I mean not the default ServiceAccount named default in the default namespace? Let's assume my ServiceAccount has the name: myServicdeAc and is created in the namespace: myNameSp.

**Comment by hasancelik** [comment]
Hi @ralphbaur,

You can use any ServiceAccount that has [required permissions](https://github.com/helm/charts/blob/master/stable/hazelcast/templates/role.yaml) from any namespace after you configured your Statefulset properly:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  ...
spec:
  replicas: 3
  serviceName: hazelcast-service
    ....
  template:
    ....
    spec:
      serviceAccountName: myServicdeAc
      containers:
        ....
```
