### ISSUE TITLE
Timeout ignored when using Kubernetes discovery

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-kubernetes#328]
When this is configured for a client, it is ignored. Timeout appears to be 60 seconds.
```
  connection-strategy:
    reconnect-mode: OFF
    connection-retry:
      cluster-connect-timeout-millis: 5000 
```

(Attempted using 5.0-SNAPSHOT)
