### ISSUE TITLE
Kubernetes API token expires on Kubernetes 1.21 and is not refreshed by hazelcast-kubernetes

### ISSUE THREAD

**Issue by Simon3** [hazelcast/hazelcast-kubernetes#415]
Hello, 

I'm reopening an issue since https://github.com/hazelcast/hazelcast-kubernetes/issues/385 was closed. 

I'm currently running a mix of Hazelcast 3 and Hazelcast 4 deployments on a GKE 1.21 cluster, using this plugin for hazelcast discovery. 

I have started getting this log once the pods reached 365 days uptime: 

`2023-01-06 15:38:10.838 ERROR 7 --- [cached.thread-3] c.hazelcast.kubernetes.KubernetesClient  : Kubernetes API authorization failure, please check your 'api-token' property`

It seems to be due to the fact that, since Kubernetes 1.21, tokens now expire. On GKE, it seems to be after 1 year. So hazelcast-kubernetes should implement a refresh mechanism (or just bump the kubernetes client lib if it uses that). 

It seems like this issue got fixed in the hazelcast/hazelcast repository (see https://github.com/hazelcast/hazelcast/issues/21461), but it means we have to upgrade to Hazelcast 5, which is not an option in my case. 

Is there any plan to fix it in this repo? Or any known workaround?

**Comment by semihbkgr** [comment]
Hello @Simon3

As this repository is deprecated, the new features and supports (in [hazelcast kubernetes discovery plugin](https://github.com/hazelcast/hazelcast/tree/master/hazelcast/src/main/java/com/hazelcast/kubernetes)) are not backported this repository.

You can get a workaround like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: sa-secret
  annotations:
    kubernetes.io/service-account.name: <service-account-name>
type: kubernetes.io/service-account-token
```

then mount the secret manually

```yaml
spec:
  serviceAccountName: <service-account-name>
  automountServiceAccountToken: false
  containers:
    - ...
      volumeMounts:
        - name: sa-volume
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
  volumes:
    - name: sa-volume
      secret:
        secretName: sa-secret
```

in this way the generated token will have no expiration.
